name: Build Java Project
# Runs the workflow on the below events
# 1. On push to the main branch
on:
  push:
    branches: ["main"]

jobs:
  Build_and_publish_jar:
    runs-on: ubuntu-latest
    # Build java project
    name: Build java project
    steps:
        # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installing java in runner
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "17"
          distribution: "temurin"

      # Installing maven in runner
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.3

        # Build java project 
      - name: Build War
        run: |
          mvn package
      
        # Upload artifact
      - name:  Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: war
          path: ./target/demo.war
